language: generic
os: linux
dist: focal
services:
  - xvfb
env:
  - UNITY_PROJECT_NAME=Test UNITY_INSTALL_DIR=/tmp/unity
cache:
  directories:
    - $UNITY_INSTALL_DIR
before_install:
  - chmod a+x ./.travis/*.sh
  - openssl aes-256-cbc -K $encrypted_21c56690ee23_key -iv $encrypted_21c56690ee23_iv -in .travis/Unity_v2021.x.ulf.enc -out .travis/Unity_v2021.x.ulf -d
install:
  - ./.travis/install.sh
script:
  - ./.travis/build.sh
after_success:
  - ./.travis/export.sh
before_deploy:
  - UNITY_DEPLOY_PACKAGE="$(ls -a release/*.zip | head -n 1)"
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: $UNITY_DEPLOY_PACKAGE
  cleanup: false
  overwrite: true
  on:
    tags: true
