language: generic
dist: focal
services:
  - xvfb
env:
  - UNITY_PROJECT_NAME=Test UNITY_INSTALL_DIR=/tmp/unity
cache:
  directories:
    - $UNITY_INSTALL_DIR
before_install:
  - chmod a+x ./.travis/*.sh
install:
  - ./.travis/install.sh
script:
  - ./.travis/build.sh
after_success:
  - ./.travis/export.sh
before_deploy:
  - UNITY_DEPLOY_PACKAGE="$(ls -a release/*.zip | head -n 1)"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $UNITY_DEPLOY_PACKAGE
  cleanup: false
  overwrite: true
  on:
    tags: true
